name: jello_mark
description: "JelloMark Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/jello-mark.png
    - assets/app_splash_screen/jello-mark-splash-screen.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/jello-mark.png
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21


flutter_native_splash:
  color: "#6B8BFF"
  image: assets/app_splash_screen/jello-mark-splash-screen.png
  android_12:
    color: "#6B8BFF"
    image: assets/app_splash_screen/jello-mark-splash-screen.png
  web: false
